### ISSUE TITLE
issue: build issue, extension installation does not work

### ISSUE THREAD

**Issue by rrrokhtar** [hadywalied/Zakker-vscode#1]
First of all good work

Looks like there is an issue with the build files, so it doesn't work when you get that downloaded from the VSCode extension marketplace 

Tested on windows vscode and WSL vscode

> mainThreadExtensionService.ts:107 Activating extension 'hadywalied.zakker' failed: Cannot find module 'sqlite3'
Require stack:
- /home/rrr/.vscode-server/extensions/hadywalied.zakker-0.1.1/dist/extension.js

logs
```
mainThreadExtensionService.ts:107 Activating extension 'hadywalied.zakker' failed: Cannot find module 'sqlite3'
Require stack:
- /home/rrr/.vscode-server/extensions/hadywalied.zakker-0.1.1/dist/extension.js
- /home/rrr/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js.
$onExtensionActivationError @ mainThreadExtensionService.ts:107
index.html?id=d5f9aea6-cb72-474a-bd7d-4417eb42ebee&origin=71f56f46-6881-449b-8e00-7ff7a6b9c4a1&swVersion=4&extensionId=hadywalied.zakker&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&remoteAuthority=wsl%2BUbuntu&purpose=webviewView:281 Found unexpected service worker controller. Found: vscode-webview://0arg6vr7f2rtqa03812p5987e7tavvta9bvd2mtthg6ttepfe1ta/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=. Expected: service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=wsl+Ubuntu. Waiting for controllerchange.
```

![image](https://github.com/user-attachments/assets/09eda11a-29ac-4991-8194-ac9679e76ee5)

**Comment by hadywalied** [comment]
Thanks a lot for the bug report, I managed to replicate and I'm working on a patch now 👌

**Comment by hadywalied** [comment]
@rrrokhtar I patched it, it should work fine now

**Comment by rrrokhtar** [comment]
@hadywalied perfect now it works on WSL 

But on windows still that issue happens 
![image](https://github.com/user-attachments/assets/74dd47e7-fb29-46fe-b9b6-72a71adcfc3c)

**Comment by hadywalied** [comment]
I couldn't get the same error, though I got an issue in sqlite3 bindings on windows for some reason.
Still investigating.

**Comment by hadywalied** [comment]
@rrrokhtar Nice Work Bro, I merged your PR and made a Release, hopefully everything works fine

**Comment by rrrokhtar** [comment]
@hadywalied works fine now 💯
